; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F103C8]
platform = ststm32
framework = arduino
board = genericSTM32F103C8
debug_tool = stlink
upload_protocol = stlink
build_flags = -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC -Os
lib_deps = 
    file://library/RF24-1.4.11.zip